### ISSUE TITLE
Missing documentation for adding a database

### ISSUE THREAD

**Issue by denisw** [futurice/futuswarm#1]
The blog post about Futuswarm mentions that adding an RDS database is possible, but there is nothing in the docs (e.g., the Quick Start) about it.

**Comment by mixman** [comment]
Reiterating, as already discussed elsewhere. To have an idea of what can be done beyond the Quick Start is browsing the CLI help (-hh) itself.

**Comment by mixman** [comment]
Quick Start amended with a database entry.
